function errorIfTagTypeUnset(obj)
if isempty(obj.Type)
    error('Tag:errorIfTagTypeUnset:typePropUnset', ...
        ['Attempted to access Tag type before the this property ' ...
        'was set. This property is set by calling the parse() ' ...
        'method.']);
end
end