function segmentTagStringAndSetPartsProperty(obj)
%SEGMENTTAGSTRINGANDSETPARTSPROPERTY Separate a tag into parts.
%   Separates TemplateText into a cell array of tag parts. The result is 
%   stored to Parts property.
%   Example: '{% if x %} y {% endif%}' produces 
%   obj.Parts = { '{% if x %}', 'y', '{% endif %}' }.

beginningTag = strtrim( ...
    obj.TemplateText(...
    obj.TagStartPatternIxs(1) : obj.TagStopPatternIxs(1)+1) ...
    );
tagContents = obj.TemplateText( ...
    obj.TagStopPatternIxs(1)+2 : obj.TagStartPatternIxs(2)-1 ...
    );
endingTag = strtrim( ...
    obj.TemplateText( ...
    obj.TagStartPatternIxs(2) : obj.TagStopPatternIxs(2)+1) ...
    );

obj.Parts = {beginningTag, tagContents, endingTag};

end