function validateTagFormat(obj)

% TODO: implement this method

% validateNumTagStartAndStopPatterns(obj);
end


% %--------------------------------------------------------------------------
% function validateNumTagStartAndStopPatterns(obj)
% % Asserts there are 2 tag start/stop patterns in TemplateText.
% assert( ...
%     numel(obj.TagStartPatternIxs) == ...
%     template.Template.ExpectedNumTagStartStopPat, ...
%     ['Invalid num. tag start patterns ("%s") in tag "%s". '...
%     'The expected number was %i.'], ...
%     template.Template.TagStartPat, obj.TemplateText, ...
%     template.Template.ExpectedNumTagStartStopPat ...
%     );
% assert( ...
%     numel(obj.TagStopPatternIxs) == ...
%     template.Template.ExpectedNumTagStartStopPat, ...
%     ['Invalid num. tag stop patterns ("%s") in tag "%s". ' ...
%     'The expected number was %i.'], ...
%     template.Template.TagEndPat, obj.TemplateText, ...
%     template.Template.ExpectedNumTagStartStopPat ...
%     );
% end